name: Broken Links Checker
on:
  schedule:
    - cron:  '0 0 1,15 * *'
  repository_dispatch:
    types: [node]

env:
  WEBSITE_URL: "https://xpiksapp.com/"
  ISSUE_TEMPLATE: ".github/workflows/check-broken-links.md"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Run Broken Links Checker
      run: npx broken-link-checker $WEBSITE_URL --ordered --recursive --exclude telegram.me --exclude vk.com --exclude pinterest.com

    - uses: actions/checkout@v3
      if: failure()

    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: ${{ env.ISSUE_TEMPLATE }}
      if: failure()
